#!/bin/sh

# Copyright By Zy143L
# Modified By Phang

[ "${ACTION}" = "released" ] || exit 0

lockfile="/tmp/toff.lock"
lockfile2="/tmp/toff2.lock"
power_led="/sys/class/leds/red:power"
delay=1
delay2=4

touch_lock() {
    touch "$lockfile"
    sleep $delay
    rm -f "$lockfile"
}

touch_lock2() {
    sleep $delay
    touch "$lockfile2"
    sleep $delay2
    rm -f "$lockfile2"
}

shutdown() {
    /etc/init.d/ledmonitor stop
    sleep 1
    /usr/bin/ledmonitor led_timer_red
    sleep 3
    /sbin/poweroff -f
}

turnled() {
    sleeping=$(uci get ledmonitor.main.sleeping)
    if [ "z""$sleeping" == "z0" ]; then
        uci set ledmonitor.main.sleeping="1"
	uci commit ledmonitor
    else
        uci set ledmonitor.main.sleeping="0"
	uci commit ledmonitor
    fi
}

restart_network() {
    /usr/bin/ledmonitor led_timer_wifi && /usr/bin/ledmonitor led_timer_mmc
    /etc/init.d/gc reload
    sleep 3
    /etc/init.d/network restart
}

if [ "$SEEN" -ge 6 ]; then
    # Press more then 6s to restart network
    restart_network
elif [ -e "$lockfile" ]; then
    # Double-click Shutdown
    rm -rf "$lockfile"
    shutdown
elif [ -e "$lockfile2" ]; then
    # Turn off/on LED
    rm -rf "$lockfile2"
    turnled
else
    touch_lock &
    touch_lock2 &
fi

return 0

