#!/bin/sh

# Copyright By Zy143L
# Modified By Phang

[ "${ACTION}" = "released" ] || exit 0

lockfile="/tmp/toff.lock"
power_led="/sys/class/leds/red:power"
delay=1

touch_lock() {
    touch "$lockfile"
    sleep $delay
    rm -f "$lockfile"
}

shutdown() {
    /etc/init.d/ledmonitor stop
    /usr/bin/ledmonitor led_off_all
    /usr/bin/ledmonitor led_timer_red
    sleep 2
    /sbin/poweroff -f
}

restart_network() {
    /usr/bin/ledmonitor led_timer_wifi && /usr/bin/ledmonitor led_timer_mmc
    /etc/init.d/gc reload
    sleep 3
    /etc/init.d/network restart
}

if [ "$SEEN" -ge 6 ]; then
    # Press more then 6s to restart network
    restart_network
elif [ -e "$lockfile" ]; then
    # Double-click Shutdown
    rm -rf "$lockfile"
    shutdown
else
    touch_lock &
fi

return 0

