#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

# Double-click Shutdown
# Copyright By Zy143L

lockfile="/tmp/toff.lock"
power_led="/sys/class/leds/red:power"
delay=1

touch_lock() {
    touch "$lockfile"
    sleep $delay
    rm -rf "$lockfile"
}

shutdown() {
    echo "timer" > "${power_led}/trigger"
    echo "1" > "${power_led}/brightness"
    /sbin/poweroff
}

restart_network() {
    /etc/init.d/gc reload
    sleep 3
    /etc/init.d/network restart
}

if [ "$SEEN" -ge 6 ]; then
    /usr/bin/ledmonitor led_timer_wifi && /usr/bin/ledmonitor led_timer_green
    restart_network
elif [ -e "$lockfile" ]; then
    rm -rf "$lockfile"
    /etc/init.d/ledmonitor stop
    sleep $delay
    /usr/bin/ledmonitor led_off_all
    shutdown
else
    touch_lock &
fi

return 0

